package com.commsen.liferay.portlet.customglobalmarkup.model.impl;

import com.commsen.liferay.portlet.customglobalmarkup.model.Markup;
import com.commsen.liferay.portlet.customglobalmarkup.service.MarkupLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Markup service. Represents a row in the &quot;CGM_Markup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MarkupImpl}.
 * </p>
 *
 * @author Milen Dyankov
 * @see MarkupImpl
 * @see com.commsen.liferay.portlet.customglobalmarkup.model.Markup
 * @generated
 */
public abstract class MarkupBaseImpl extends MarkupModelImpl implements Markup {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a markup model instance should use the {@link Markup} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            MarkupLocalServiceUtil.addMarkup(this);
        } else {
            MarkupLocalServiceUtil.updateMarkup(this);
        }
    }
}
