package com.commsen.liferay.portlet.customglobalmarkup.model.impl;

import com.commsen.liferay.portlet.customglobalmarkup.model.Markup;
import com.commsen.liferay.portlet.customglobalmarkup.model.MarkupModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

/**
 * The base model implementation for the Markup service. Represents a row in the &quot;CGM_Markup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.commsen.liferay.portlet.customglobalmarkup.model.MarkupModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MarkupImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a markup model instance should use the {@link com.commsen.liferay.portlet.customglobalmarkup.model.Markup} interface instead.
 * </p>
 *
 * @author Milen Dyankov
 * @see MarkupImpl
 * @see com.commsen.liferay.portlet.customglobalmarkup.model.Markup
 * @see com.commsen.liferay.portlet.customglobalmarkup.model.MarkupModel
 * @generated
 */
public class MarkupModelImpl extends BaseModelImpl<Markup>
    implements MarkupModel {
    public static final String TABLE_NAME = "CGM_Markup";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", new Integer(Types.BIGINT) },
            { "companyId", new Integer(Types.BIGINT) },
            { "groupId", new Integer(Types.BIGINT) },
            { "markup", new Integer(Types.VARCHAR) },
            { "active_", new Integer(Types.BOOLEAN) },
            { "location", new Integer(Types.INTEGER) }
        };
    public static final String TABLE_SQL_CREATE = "create table CGM_Markup (id_ LONG not null primary key,companyId LONG,groupId LONG,markup VARCHAR(75) null,active_ BOOLEAN,location INTEGER)";
    public static final String TABLE_SQL_DROP = "drop table CGM_Markup";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.commsen.liferay.portlet.customglobalmarkup.model.Markup"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.commsen.liferay.portlet.customglobalmarkup.model.Markup"),
            true);
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.commsen.liferay.portlet.customglobalmarkup.model.Markup"));
    private long _id;
    private long _companyId;
    private long _groupId;
    private String _markup;
    private boolean _active;
    private short _location;
    private transient ExpandoBridge _expandoBridge;

    public MarkupModelImpl() {
    }

    public long getPrimaryKey() {
        return _id;
    }

    public void setPrimaryKey(long pk) {
        setId(pk);
    }

    public Serializable getPrimaryKeyObj() {
        return new Long(_id);
    }

    public long getId() {
        return _id;
    }

    public void setId(long id) {
        _id = id;
    }

    public long getCompanyId() {
        return _companyId;
    }

    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    public long getGroupId() {
        return _groupId;
    }

    public void setGroupId(long groupId) {
        _groupId = groupId;
    }

    public String getMarkup() {
        if (_markup == null) {
            return StringPool.BLANK;
        } else {
            return _markup;
        }
    }

    public void setMarkup(String markup) {
        _markup = markup;
    }

    public boolean getActive() {
        return _active;
    }

    public boolean isActive() {
        return _active;
    }

    public void setActive(boolean active) {
        _active = active;
    }

    public short getLocation() {
        return _location;
    }

    public void setLocation(short location) {
        _location = location;
    }

    public Markup toEscapedModel() {
        if (isEscapedModel()) {
            return (Markup) this;
        } else {
            return (Markup) Proxy.newProxyInstance(Markup.class.getClassLoader(),
                new Class[] { Markup.class }, new AutoEscapeBeanHandler(this));
        }
    }

    public ExpandoBridge getExpandoBridge() {
        if (_expandoBridge == null) {
            _expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
                    Markup.class.getName(), getPrimaryKey());
        }

        return _expandoBridge;
    }

    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        getExpandoBridge().setAttributes(serviceContext);
    }

    public Object clone() {
        MarkupImpl markupImpl = new MarkupImpl();

        markupImpl.setId(getId());

        markupImpl.setCompanyId(getCompanyId());

        markupImpl.setGroupId(getGroupId());

        markupImpl.setMarkup(getMarkup());

        markupImpl.setActive(getActive());

        markupImpl.setLocation(getLocation());

        return markupImpl;
    }

    public int compareTo(Markup markup) {
        long pk = markup.getPrimaryKey();

        if (getPrimaryKey() < pk) {
            return -1;
        } else if (getPrimaryKey() > pk) {
            return 1;
        } else {
            return 0;
        }
    }

    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        Markup markup = null;

        try {
            markup = (Markup) obj;
        } catch (ClassCastException cce) {
            return false;
        }

        long pk = markup.getPrimaryKey();

        if (getPrimaryKey() == pk) {
            return true;
        } else {
            return false;
        }
    }

    public int hashCode() {
        return (int) getPrimaryKey();
    }

    public String toString() {
        StringBundler sb = new StringBundler(13);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", markup=");
        sb.append(getMarkup());
        sb.append(", active=");
        sb.append(getActive());
        sb.append(", location=");
        sb.append(getLocation());
        sb.append("}");

        return sb.toString();
    }

    public String toXmlString() {
        StringBundler sb = new StringBundler(22);

        sb.append("<model><model-name>");
        sb.append("com.commsen.liferay.portlet.customglobalmarkup.model.Markup");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>markup</column-name><column-value><![CDATA[");
        sb.append(getMarkup());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>active</column-name><column-value><![CDATA[");
        sb.append(getActive());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>location</column-name><column-value><![CDATA[");
        sb.append(getLocation());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
