package com.commsen.liferay.portlet.customglobalmarkup.model.impl;

import com.commsen.liferay.portlet.customglobalmarkup.model.Markup;
import com.commsen.liferay.portlet.customglobalmarkup.model.MarkupModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

/**
 * The base model implementation for the Markup service. Represents a row in the &quot;CGM_Markup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.commsen.liferay.portlet.customglobalmarkup.model.MarkupModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MarkupImpl}.
 * </p>
 *
 * @author Milen Dyankov
 * @see MarkupImpl
 * @see com.commsen.liferay.portlet.customglobalmarkup.model.Markup
 * @see com.commsen.liferay.portlet.customglobalmarkup.model.MarkupModel
 * @generated
 */
public class MarkupModelImpl extends BaseModelImpl<Markup>
    implements MarkupModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a markup model instance should use the {@link com.commsen.liferay.portlet.customglobalmarkup.model.Markup} interface instead.
     */
    public static final String TABLE_NAME = "CGM_Markup";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "markup", Types.VARCHAR },
            { "active_", Types.BOOLEAN },
            { "location", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table CGM_Markup (id_ LONG not null primary key,companyId LONG,groupId LONG,markup VARCHAR(2000) null,active_ BOOLEAN,location INTEGER)";
    public static final String TABLE_SQL_DROP = "drop table CGM_Markup";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.commsen.liferay.portlet.customglobalmarkup.model.Markup"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.commsen.liferay.portlet.customglobalmarkup.model.Markup"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.commsen.liferay.portlet.customglobalmarkup.model.Markup"),
            true);
    public static long ACTIVE_COLUMN_BITMASK = 1L;
    public static long COMPANYID_COLUMN_BITMASK = 2L;
    public static long GROUPID_COLUMN_BITMASK = 4L;
    public static long LOCATION_COLUMN_BITMASK = 8L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.commsen.liferay.portlet.customglobalmarkup.model.Markup"));
    private static ClassLoader _classLoader = Markup.class.getClassLoader();
    private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
            Markup.class
        };
    private long _id;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private String _markup;
    private boolean _active;
    private boolean _originalActive;
    private boolean _setOriginalActive;
    private short _location;
    private short _originalLocation;
    private boolean _setOriginalLocation;
    private transient ExpandoBridge _expandoBridge;
    private long _columnBitmask;
    private Markup _escapedModelProxy;

    public MarkupModelImpl() {
    }

    public long getPrimaryKey() {
        return _id;
    }

    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    public Serializable getPrimaryKeyObj() {
        return new Long(_id);
    }

    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    public Class<?> getModelClass() {
        return Markup.class;
    }

    public String getModelClassName() {
        return Markup.class.getName();
    }

    public long getId() {
        return _id;
    }

    public void setId(long id) {
        _id = id;
    }

    public long getCompanyId() {
        return _companyId;
    }

    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    public long getGroupId() {
        return _groupId;
    }

    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    public String getMarkup() {
        if (_markup == null) {
            return StringPool.BLANK;
        } else {
            return _markup;
        }
    }

    public void setMarkup(String markup) {
        _markup = markup;
    }

    public boolean getActive() {
        return _active;
    }

    public boolean isActive() {
        return _active;
    }

    public void setActive(boolean active) {
        _columnBitmask |= ACTIVE_COLUMN_BITMASK;

        if (!_setOriginalActive) {
            _setOriginalActive = true;

            _originalActive = _active;
        }

        _active = active;
    }

    public boolean getOriginalActive() {
        return _originalActive;
    }

    public short getLocation() {
        return _location;
    }

    public void setLocation(short location) {
        _columnBitmask |= LOCATION_COLUMN_BITMASK;

        if (!_setOriginalLocation) {
            _setOriginalLocation = true;

            _originalLocation = _location;
        }

        _location = location;
    }

    public short getOriginalLocation() {
        return _originalLocation;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public Markup toEscapedModel() {
        if (_escapedModelProxy == null) {
            _escapedModelProxy = (Markup) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelProxyInterfaces,
                    new AutoEscapeBeanHandler(this));
        }

        return _escapedModelProxy;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        if (_expandoBridge == null) {
            _expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
                    Markup.class.getName(), getPrimaryKey());
        }

        return _expandoBridge;
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        getExpandoBridge().setAttributes(serviceContext);
    }

    @Override
    public Object clone() {
        MarkupImpl markupImpl = new MarkupImpl();

        markupImpl.setId(getId());
        markupImpl.setCompanyId(getCompanyId());
        markupImpl.setGroupId(getGroupId());
        markupImpl.setMarkup(getMarkup());
        markupImpl.setActive(getActive());
        markupImpl.setLocation(getLocation());

        markupImpl.resetOriginalValues();

        return markupImpl;
    }

    public int compareTo(Markup markup) {
        long primaryKey = markup.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        Markup markup = null;

        try {
            markup = (Markup) obj;
        } catch (ClassCastException cce) {
            return false;
        }

        long primaryKey = markup.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        MarkupModelImpl markupModelImpl = this;

        markupModelImpl._originalCompanyId = markupModelImpl._companyId;

        markupModelImpl._setOriginalCompanyId = false;

        markupModelImpl._originalGroupId = markupModelImpl._groupId;

        markupModelImpl._setOriginalGroupId = false;

        markupModelImpl._originalActive = markupModelImpl._active;

        markupModelImpl._setOriginalActive = false;

        markupModelImpl._originalLocation = markupModelImpl._location;

        markupModelImpl._setOriginalLocation = false;

        markupModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Markup> toCacheModel() {
        MarkupCacheModel markupCacheModel = new MarkupCacheModel();

        markupCacheModel.id = getId();

        markupCacheModel.companyId = getCompanyId();

        markupCacheModel.groupId = getGroupId();

        markupCacheModel.markup = getMarkup();

        String markup = markupCacheModel.markup;

        if ((markup != null) && (markup.length() == 0)) {
            markupCacheModel.markup = null;
        }

        markupCacheModel.active = getActive();

        markupCacheModel.location = getLocation();

        return markupCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(13);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", markup=");
        sb.append(getMarkup());
        sb.append(", active=");
        sb.append(getActive());
        sb.append(", location=");
        sb.append(getLocation());
        sb.append("}");

        return sb.toString();
    }

    public String toXmlString() {
        StringBundler sb = new StringBundler(22);

        sb.append("<model><model-name>");
        sb.append("com.commsen.liferay.portlet.customglobalmarkup.model.Markup");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>markup</column-name><column-value><![CDATA[");
        sb.append(getMarkup());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>active</column-name><column-value><![CDATA[");
        sb.append(getActive());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>location</column-name><column-value><![CDATA[");
        sb.append(getLocation());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
