package com.commsen.liferay.portlet.customglobalmarkup.service.base;

import com.commsen.liferay.portlet.customglobalmarkup.model.Markup;
import com.commsen.liferay.portlet.customglobalmarkup.service.MarkupLocalService;
import com.commsen.liferay.portlet.customglobalmarkup.service.persistence.MarkupPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the markup local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.commsen.liferay.portlet.customglobalmarkup.service.impl.MarkupLocalServiceImpl}.
 * </p>
 *
 * @author Milen Dyankov
 * @see com.commsen.liferay.portlet.customglobalmarkup.service.impl.MarkupLocalServiceImpl
 * @see com.commsen.liferay.portlet.customglobalmarkup.service.MarkupLocalServiceUtil
 * @generated
 */
public abstract class MarkupLocalServiceBaseImpl implements MarkupLocalService,
    IdentifiableBean {
    private static Log _log = LogFactoryUtil.getLog(MarkupLocalServiceBaseImpl.class);
    @BeanReference(type = MarkupLocalService.class)
    protected MarkupLocalService markupLocalService;
    @BeanReference(type = MarkupPersistence.class)
    protected MarkupPersistence markupPersistence;
    @BeanReference(type = CounterLocalService.class)
    protected CounterLocalService counterLocalService;
    @BeanReference(type = ResourceLocalService.class)
    protected ResourceLocalService resourceLocalService;
    @BeanReference(type = ResourceService.class)
    protected ResourceService resourceService;
    @BeanReference(type = ResourcePersistence.class)
    protected ResourcePersistence resourcePersistence;
    @BeanReference(type = UserLocalService.class)
    protected UserLocalService userLocalService;
    @BeanReference(type = UserService.class)
    protected UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.commsen.liferay.portlet.customglobalmarkup.service.MarkupLocalServiceUtil} to access the markup local service.
     */

    /**
     * Adds the markup to the database. Also notifies the appropriate model listeners.
     *
     * @param markup the markup
     * @return the markup that was added
     * @throws SystemException if a system exception occurred
     */
    public Markup addMarkup(Markup markup) throws SystemException {
        markup.setNew(true);

        markup = markupPersistence.update(markup, false);

        Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

        if (indexer != null) {
            try {
                indexer.reindex(markup);
            } catch (SearchException se) {
                if (_log.isWarnEnabled()) {
                    _log.warn(se, se);
                }
            }
        }

        return markup;
    }

    /**
     * Creates a new markup with the primary key. Does not add the markup to the database.
     *
     * @param id the primary key for the new markup
     * @return the new markup
     */
    public Markup createMarkup(long id) {
        return markupPersistence.create(id);
    }

    /**
     * Deletes the markup with the primary key from the database. Also notifies the appropriate model listeners.
     *
     * @param id the primary key of the markup
     * @throws PortalException if a markup with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    public void deleteMarkup(long id) throws PortalException, SystemException {
        Markup markup = markupPersistence.remove(id);

        Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

        if (indexer != null) {
            try {
                indexer.delete(markup);
            } catch (SearchException se) {
                if (_log.isWarnEnabled()) {
                    _log.warn(se, se);
                }
            }
        }
    }

    /**
     * Deletes the markup from the database. Also notifies the appropriate model listeners.
     *
     * @param markup the markup
     * @throws SystemException if a system exception occurred
     */
    public void deleteMarkup(Markup markup) throws SystemException {
        markupPersistence.remove(markup);

        Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

        if (indexer != null) {
            try {
                indexer.delete(markup);
            } catch (SearchException se) {
                if (_log.isWarnEnabled()) {
                    _log.warn(se, se);
                }
            }
        }
    }

    /**
     * Performs a dynamic query on the database and returns the matching rows.
     *
     * @param dynamicQuery the dynamic query
     * @return the matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery)
        throws SystemException {
        return markupPersistence.findWithDynamicQuery(dynamicQuery);
    }

    /**
     * Performs a dynamic query on the database and returns a range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @return the range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
        throws SystemException {
        return markupPersistence.findWithDynamicQuery(dynamicQuery, start, end);
    }

    /**
     * Performs a dynamic query on the database and returns an ordered range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
     * @return the ordered range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
        OrderByComparator orderByComparator) throws SystemException {
        return markupPersistence.findWithDynamicQuery(dynamicQuery, start, end,
            orderByComparator);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    public long dynamicQueryCount(DynamicQuery dynamicQuery)
        throws SystemException {
        return markupPersistence.countWithDynamicQuery(dynamicQuery);
    }

    public Markup fetchMarkup(long id) throws SystemException {
        return markupPersistence.fetchByPrimaryKey(id);
    }

    /**
     * Returns the markup with the primary key.
     *
     * @param id the primary key of the markup
     * @return the markup
     * @throws PortalException if a markup with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    public Markup getMarkup(long id) throws PortalException, SystemException {
        return markupPersistence.findByPrimaryKey(id);
    }

    public PersistedModel getPersistedModel(Serializable primaryKeyObj)
        throws PortalException, SystemException {
        return markupPersistence.findByPrimaryKey(primaryKeyObj);
    }

    /**
     * Returns a range of all the markups.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param start the lower bound of the range of markups
     * @param end the upper bound of the range of markups (not inclusive)
     * @return the range of markups
     * @throws SystemException if a system exception occurred
     */
    public List<Markup> getMarkups(int start, int end)
        throws SystemException {
        return markupPersistence.findAll(start, end);
    }

    /**
     * Returns the number of markups.
     *
     * @return the number of markups
     * @throws SystemException if a system exception occurred
     */
    public int getMarkupsCount() throws SystemException {
        return markupPersistence.countAll();
    }

    /**
     * Updates the markup in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param markup the markup
     * @return the markup that was updated
     * @throws SystemException if a system exception occurred
     */
    public Markup updateMarkup(Markup markup) throws SystemException {
        return updateMarkup(markup, true);
    }

    /**
     * Updates the markup in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param markup the markup
     * @param merge whether to merge the markup with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
     * @return the markup that was updated
     * @throws SystemException if a system exception occurred
     */
    public Markup updateMarkup(Markup markup, boolean merge)
        throws SystemException {
        markup.setNew(false);

        markup = markupPersistence.update(markup, merge);

        Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

        if (indexer != null) {
            try {
                indexer.reindex(markup);
            } catch (SearchException se) {
                if (_log.isWarnEnabled()) {
                    _log.warn(se, se);
                }
            }
        }

        return markup;
    }

    /**
     * Returns the markup local service.
     *
     * @return the markup local service
     */
    public MarkupLocalService getMarkupLocalService() {
        return markupLocalService;
    }

    /**
     * Sets the markup local service.
     *
     * @param markupLocalService the markup local service
     */
    public void setMarkupLocalService(MarkupLocalService markupLocalService) {
        this.markupLocalService = markupLocalService;
    }

    /**
     * Returns the markup persistence.
     *
     * @return the markup persistence
     */
    public MarkupPersistence getMarkupPersistence() {
        return markupPersistence;
    }

    /**
     * Sets the markup persistence.
     *
     * @param markupPersistence the markup persistence
     */
    public void setMarkupPersistence(MarkupPersistence markupPersistence) {
        this.markupPersistence = markupPersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the resource remote service.
     *
     * @return the resource remote service
     */
    public ResourceService getResourceService() {
        return resourceService;
    }

    /**
     * Sets the resource remote service.
     *
     * @param resourceService the resource remote service
     */
    public void setResourceService(ResourceService resourceService) {
        this.resourceService = resourceService;
    }

    /**
     * Returns the resource persistence.
     *
     * @return the resource persistence
     */
    public ResourcePersistence getResourcePersistence() {
        return resourcePersistence;
    }

    /**
     * Sets the resource persistence.
     *
     * @param resourcePersistence the resource persistence
     */
    public void setResourcePersistence(ResourcePersistence resourcePersistence) {
        this.resourcePersistence = resourcePersistence;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        PersistedModelLocalServiceRegistryUtil.register("com.commsen.liferay.portlet.customglobalmarkup.model.Markup",
            markupLocalService);
    }

    public void destroy() {
        PersistedModelLocalServiceRegistryUtil.unregister(
            "com.commsen.liferay.portlet.customglobalmarkup.model.Markup");
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    protected Class<?> getModelClass() {
        return Markup.class;
    }

    protected String getModelClassName() {
        return Markup.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = markupPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
